clear; clc; close all;
script_dir = fileparts(mfilename('fullpath'));
project_root = fileparts(fileparts(script_dir));
addpath(fullfile(project_root, 'utilities'), '-begin');
project_root = get_project_root(project_root);
cleanup_path = ensure_project_on_path(project_root); %#ok<NASGU>
paths = build_project_paths(project_root);

params = get_fiber_optimization_params('fast');
topo = load(paths.topology_file);
[material_mask, ~] = clean_material_mask(topo.struc, params.init.min_component_size, params.init.morph_radius);
material_mask_full = expand_material_mask_to_full(material_mask);

delta_phi = params.levelset.delta_phi_factor * params.grid.h;
[lsf, ~, ~] = construct_boundary_offset_levelset_with_parallel( ...
    material_mask, params.grid.nelx, params.grid.nely, ...
    params.grid.dx, params.grid.dy, delta_phi, struct('morph_radius', params.init.morph_radius));

current_state = evaluate_candidate_state(lsf, [], params.opt.delta_theta_max, ...
    params.grid.dx, params.grid.dy, params.grid.nelx, params.grid.nely, material_mask, ...
    params.material.E_L, params.material.E_T, params.material.nu_LT, params.material.G_LT, ...
    params.material.thickness, params.load.F_mag, params.smooth.eta, params.smooth.iterations);
theta_prev = current_state.theta;
theta_only_state = evaluate_candidate_state(lsf, theta_prev, params.opt.delta_theta_max, ...
    params.grid.dx, params.grid.dy, params.grid.nelx, params.grid.nely, material_mask, ...
    params.material.E_L, params.material.E_T, params.material.nu_LT, params.material.G_LT, ...
    params.material.thickness, params.load.F_mag, params.smooth.eta, params.smooth.iterations);

dC_dtheta_next = compute_sensitivity_adjoint(params.grid.nelx, params.grid.nely, ...
    theta_only_state.U, theta_only_state.theta, params.material.E_L, params.material.E_T, ...
    params.material.nu_LT, params.material.G_LT, params.material.thickness, ...
    params.grid.dx, params.grid.dy, material_mask, false);
[pullback, ~] = differentiate_theta_transition_exact(dC_dtheta_next, theta_only_state.theta_transition_cache, ...
    struct('limiter_mode', 'hard', ...
           'soft_limiter_beta', params.gradient.soft_limiter_beta, ...
           'grad_floor', params.gradient.theta_raw_grad_floor));

g_exact = aggregate_node_sensitivity(pullback, [], lsf, params.grid.nelx, params.grid.nely, ...
    params.grid.dx, params.grid.dy, true(size(lsf)));
[audit_mask, ~] = build_theta_transition_audit_support( ...
    theta_only_state.theta_transition_cache, ...
    struct('material_mask_full', material_mask_full, ...
           'support_mode', 'full', ...
           'grad_floor', params.gradient.theta_raw_grad_floor, ...
           'branch_cut_tol', params.gradient.theta_raw_branch_cut_tol));

support_mask = audit_mask & abs(g_exact) > 1e-12;
if ~any(support_mask(:))
    support_mask = audit_mask;
end

descent_dir = g_exact;
descent_dir(~support_mask) = 0;
dir_norm = norm(descent_dir(:));
assert(dir_norm > 0, 'exact 直接 phi 下降 smoke: 可用下降方向为空。');
descent_dir = descent_dir / dir_norm;

eps_phi = 1e-5 * max(norm(lsf(support_mask)), params.grid.h);
C_current = evaluate_candidate_compliance(lsf, theta_prev, params.opt.delta_theta_max, ...
    params.grid.dx, params.grid.dy, params.grid.nelx, params.grid.nely, material_mask, ...
    params.material.E_L, params.material.E_T, params.material.nu_LT, params.material.G_LT, ...
    params.material.thickness, params.load.F_mag, params.smooth.eta, params.smooth.iterations);
C_new = evaluate_candidate_compliance(lsf - eps_phi * descent_dir, theta_prev, params.opt.delta_theta_max, ...
    params.grid.dx, params.grid.dy, params.grid.nelx, params.grid.nely, material_mask, ...
    params.material.E_L, params.material.E_T, params.material.nu_LT, params.material.G_LT, ...
    params.material.thickness, params.load.F_mag, params.smooth.eta, params.smooth.iterations);

fprintf('=== exact direct phi descent smoke ===\n');
fprintf('C_current = %.6e\n', C_current);
fprintf('C_new     = %.6e\n', C_new);
fprintf('delta     = %.6e\n', C_new - C_current);

assert(C_new < C_current, '精确链直接 phi 下降验证失败：未产生下降。');
fprintf('PASS: exact direct phi descent smoke.\n');

function mask_full = expand_material_mask_to_full(mask_core)
mask_full = false(size(mask_core, 1) + 2, size(mask_core, 2) + 2);
mask_full(2:end-1, 2:end-1) = logical(mask_core);
mask_full(1, :) = mask_full(2, :);
mask_full(end, :) = mask_full(end-1, :);
mask_full(:, 1) = mask_full(:, 2);
mask_full(:, end) = mask_full(:, end-1);
end
