function path_quality_history = build_path_quality_history(raw_turn_history, raw_kappa_history, ...
    raw_spacing_error_history, raw_grad_dev_history, raw_near_zero_outlier_history)
%BUILD_PATH_QUALITY_HISTORY Build the path-quality history struct.

    path_quality_history = struct( ...
        'mean_abs_turn_deg', raw_turn_history, ...
        'max_abs_kappa', raw_kappa_history, ...
        'parallel_spacing_error_percent', raw_spacing_error_history, ...
        'grad_dev_mean', raw_grad_dev_history, ...
        'near_zero_grad_outlier_ratio', raw_near_zero_outlier_history);
end
