function fiber_log_sensitivity_velocity_summary(log_in)
%FIBER_LOG_SENSITIVITY_VELOCITY_SUMMARY Emit sensitivity/velocity summary diagnostics.

    if ~(log_in.iter == 1 || mod(log_in.iter, 10) == 0)
        return;
    end

    fprintf('  节点灵敏度统计：最大=%.3e，最小=%.3e，平均=%.3e\n', ...
        max(log_in.node_sensitivity(:)), min(log_in.node_sensitivity(:)), ...
        mean(abs(log_in.node_sensitivity(:))));
    fprintf('  速度场统计：最大=%.3e，最小=%.3e，平均=%.3e\n', ...
        max(log_in.velocity(:)), min(log_in.velocity(:)), mean(abs(log_in.velocity(:))));
    fprintf('  窄带速度：平均=%.3e，加权平均=%.3e，最大=%.3e，正向=%.1f%%，负向=%.1f%%\n', ...
        log_in.velocity_stats.mean_band, log_in.velocity_stats.weighted_mean, ...
        log_in.velocity_stats.max_band, log_in.velocity_stats.pos_ratio * 100, ...
        log_in.velocity_stats.neg_ratio * 100);
    fprintf('  界面长度=%.3f，质心=(%.3f, %.3f)\n', ...
        log_in.velocity_stats.length, log_in.velocity_stats.centroid(1), log_in.velocity_stats.centroid(2));
    predicted_change = log_in.velocity_stats.max_band * log_in.dt_adaptive;
    fprintf('  预测最大角度变化 %.2f 度\n', predicted_change * 180 / pi);
    fprintf('  自适应时间步长: %.3e (CFL=%.3e, Δθ约束=%.3e)\n', ...
        log_in.dt_adaptive, log_in.dt_cfl, log_in.dt_angle);
    diag_report(log_in.iter, log_in.node_sensitivity, log_in.velocity_stats);
end
