function validate_params(params)
    % 参数合理性检查
    % 
    % 输入：
    %   params - 参数结构体
    %
    % 功能：
    %   验证所有参数的合理性，不合理的参数会抛出错误
    
    % 网格参数
    assert(params.grid.nelx > 0 && params.grid.nely > 0, ...
        '网格尺寸必须为正整数');
    assert(mod(params.grid.nelx, 1) == 0 && mod(params.grid.nely, 1) == 0, ...
        '网格尺寸必须为整数');
    assert(params.grid.Lx > 0 && params.grid.Ly > 0, ...
        '结构尺寸必须为正数');
    assert(params.grid.dx < params.grid.Lx && params.grid.dy < params.grid.Ly, ...
        '单元尺寸不合理');
    assert(params.grid.h > 0, ...
        '网格特征尺寸h必须为正');
    
    % 优化参数
    assert(params.opt.max_iter > 0 && params.opt.max_iter <= 10000, ...
        '最大迭代次数必须在(0, 10000]范围内');
    assert(params.opt.tol > 0 && params.opt.tol < 1, ...
        '收敛容差必须在(0, 1)范围内');
    assert(params.opt.alpha >= 0 && params.opt.alpha <= 1, ...
        'alpha参数必须在[0, 1]范围内');
    assert(params.opt.delta_theta_max > 0 && params.opt.delta_theta_max < pi, ...
        'delta_theta_max必须在(0, π)范围内');
    assert(params.opt.acceptance_tol >= 0 && params.opt.acceptance_tol < 1, ...
        'acceptance_tol必须在[0, 1)范围内');
    assert(islogical(params.opt.enable_current_state_guard) || isnumeric(params.opt.enable_current_state_guard), ...
        'enable_current_state_guard必须为逻辑值');
    assert(params.opt.current_state_tol >= 0 && params.opt.current_state_tol < 1, ...
        'current_state_tol必须在[0, 1)范围内');
    assert(params.opt.current_guard_start_iter >= 1 && mod(params.opt.current_guard_start_iter,1)==0, ...
        'current_guard_start_iter必须为正整数');
    assert(islogical(params.opt.enable_reinit_current_guard) || isnumeric(params.opt.enable_reinit_current_guard), ...
        'enable_reinit_current_guard必须为逻辑值');
    assert(params.opt.reinit_current_tol >= 0 && params.opt.reinit_current_tol < 1, ...
        'reinit_current_tol必须在[0, 1)范围内');
    assert(params.opt.reinit_guard_start_iter >= 1 && mod(params.opt.reinit_guard_start_iter,1)==0, ...
        'reinit_guard_start_iter必须为正整数');
    assert(params.opt.backtrack_factor > 0 && params.opt.backtrack_factor < 1, ...
        'backtrack_factor必须在(0, 1)范围内');
    assert(params.opt.max_backtrack >= 0 && mod(params.opt.max_backtrack,1)==0, ...
        'max_backtrack必须为非负整数');
    assert(params.opt.min_backtrack_dt > 0, ...
        'min_backtrack_dt必须为正数');
    assert(islogical(params.opt.enable_best_state_guard) || isnumeric(params.opt.enable_best_state_guard), ...
        'enable_best_state_guard必须为逻辑值');
    assert(params.opt.best_state_rel_tol >= 0 && params.opt.best_state_rel_tol < 1, ...
        'best_state_rel_tol必须在[0, 1)范围内');
    assert(params.opt.best_state_patience >= 1 && mod(params.opt.best_state_patience,1)==0, ...
        'best_state_patience必须为正整数');
    assert(params.opt.theta_only_fuse_limit >= 1 && mod(params.opt.theta_only_fuse_limit,1)==0, ...
        'theta_only_fuse_limit必须为正整数');
    
    % 材料参数
    assert(params.material.E_L > params.material.E_T, ...
        '正交各向异性材料：纵向模量应大于横向模量');
    assert(params.material.E_L > 0 && params.material.E_T > 0, ...
        '杨氏模量必须为正');
    assert(params.material.nu_LT > 0 && params.material.nu_LT < 0.5, ...
        '泊松比必须在(0, 0.5)范围内');
    assert(params.material.G_LT > 0, ...
        '剪切模量必须为正');
    assert(params.material.thickness > 0, ...
        '板厚必须为正');
    
    % 水平集参数
    assert(params.levelset.delta_phi_factor > 0 && ...
           params.levelset.delta_phi_factor < 2, ...
        'delta_phi因子应在(0, 2)范围内');
    assert(params.levelset.reinit_freq_early > 0, ...
        '前期重初始化频率必须为正整数');
    assert(params.levelset.reinit_freq_late > 0, ...
        '后期重初始化频率必须为正整数');
    assert(params.levelset.reinit_threshold > 0 && ...
           params.levelset.reinit_threshold < 2, ...
        '重初始化阈值应在(0, 2)范围内');
    assert(params.levelset.reinit_max_interval > 0, ...
        '最大重初始化间隔必须为正');
    assert(any(strcmpi(params.levelset.reinit_domain, {'masked', 'full'})), ...
        'reinit_domain必须为''masked''或''full''');
    assert(ismember(params.levelset.advection_order, [1, 2]), ...
        'advection_order必须为1或2');
    assert(ismember(lower(params.levelset.time_integrator), {'euler', 'ssprk2'}), ...
        'time_integrator必须为euler或ssprk2');
    assert(ismember(lower(params.levelset.reinit_method), {'masked_fmm', 'subcell_signed_distance'}), ...
        'reinit_method必须为masked_fmm或subcell_signed_distance');
    assert(islogical(params.levelset.fallback_first_order) || isnumeric(params.levelset.fallback_first_order), ...
        'fallback_first_order必须为逻辑值');
    assert(islogical(params.levelset.freeze_on_incomplete_godunov) || isnumeric(params.levelset.freeze_on_incomplete_godunov), ...
        'freeze_on_incomplete_godunov必须为逻辑值');
    assert(params.levelset.eno_smoothness_factor > 0, ...
        'eno_smoothness_factor必须为正');
    assert(params.levelset.stencil_buffer_cells >= 0 && mod(params.levelset.stencil_buffer_cells, 1) == 0, ...
        'stencil_buffer_cells必须为非负整数');
    assert(isfield(params.levelset, 'hj_rhs_mode') && ...
        ismember(lower(string(params.levelset.hj_rhs_mode)), {'legacy', 'indexed', 'vectorized_first_order'}), ...
        'hj_rhs_mode必须为legacy/indexed/vectorized_first_order之一');
    assert(params.levelset.boundary_guard_band_factor >= 0, ...
        'boundary_guard_band_factor必须为非负数');
    assert(params.levelset.local_reinit_zero_band_factor > 0, ...
        'local_reinit_zero_band_factor必须为正');
    assert(params.levelset.local_reinit_buffer_cells >= 0 && mod(params.levelset.local_reinit_buffer_cells, 1) == 0, ...
        'local_reinit_buffer_cells必须为非负整数');
    assert(params.levelset.refresh_interval >= 1 && mod(params.levelset.refresh_interval, 1) == 0, ...
        'refresh_interval必须为正整数');
    assert(params.levelset.refresh_buffer_cells >= 0 && mod(params.levelset.refresh_buffer_cells, 1) == 0, ...
        'refresh_buffer_cells必须为非负整数');
    assert(params.levelset.zero_geometry_min_points >= 2 && mod(params.levelset.zero_geometry_min_points, 1) == 0, ...
        'zero_geometry_min_points必须为不小于2的整数');
    assert(params.levelset.zero_geometry_min_length > 0, ...
        'zero_geometry_min_length必须为正');
    
    % 投影参数
    assert(params.projection.omega_early >= 0 && ...
           params.projection.omega_early <= 1, ...
        '前期投影强度必须在[0, 1]范围内');
    assert(params.projection.omega_late >= 0 && ...
           params.projection.omega_late <= 1, ...
        '后期投影强度必须在[0, 1]范围内');
    
    % 平滑参数
    assert(params.smooth.eta > 0 && params.smooth.eta < 0.5, ...
        '平滑系数eta应在(0, 0.5)范围内');
    assert(params.smooth.iterations > 0 && params.smooth.iterations <= 10, ...
        '平滑迭代次数应在(0, 10]范围内');

    % 速度场参数
    assert(islogical(params.velocity.enable_bias_removal) || isnumeric(params.velocity.enable_bias_removal), ...
        'enable_bias_removal必须为逻辑值');
    assert(params.velocity.bias_beta >= 0 && params.velocity.bias_beta <= 1, ...
        'bias_beta必须在[0, 1]范围内');
    assert(params.velocity.scale_quantile > 0 && params.velocity.scale_quantile <= 100, ...
        'scale_quantile必须在(0, 100]范围内');
    assert(params.velocity.clip_abs > 0 || isinf(params.velocity.clip_abs), ...
        'clip_abs必须为正数或inf');

    % 梯度链参数
    if isfield(params, 'gradient')
        assert(ismember(lower(string(params.gradient.chain_mode)), {'legacy', 'shadow', 'exact'}), ...
            'gradient.chain_mode必须为legacy/shadow/exact之一');
        assert(ismember(lower(string(params.gradient.limiter_mode)), {'hard', 'soft_experiment'}), ...
            'gradient.limiter_mode必须为hard/soft_experiment之一');
        assert(ismember(lower(string(params.gradient.audit_support_mode)), {'full', 'opt'}), ...
            'gradient.audit_support_mode必须为full/opt之一');
        assert(params.gradient.shadow_topk >= 1 && mod(params.gradient.shadow_topk, 1) == 0, ...
            'gradient.shadow_topk必须为正整数');
        assert(params.gradient.shadow_num_directional_checks >= 1 && ...
            mod(params.gradient.shadow_num_directional_checks, 1) == 0, ...
            'gradient.shadow_num_directional_checks必须为正整数');
        assert(params.gradient.shadow_fd_eps_factor > 0, ...
            'gradient.shadow_fd_eps_factor必须为正');
        assert(params.gradient.soft_limiter_beta > 0, ...
            'gradient.soft_limiter_beta必须为正');
        assert(params.gradient.theta_raw_grad_floor >= 0, ...
            'gradient.theta_raw_grad_floor必须为非负');
        assert(params.gradient.theta_raw_branch_cut_tol >= 0, ...
            'gradient.theta_raw_branch_cut_tol必须为非负');
    end

    % 制造约束参数
    if isfield(params, 'manufacturing')
        assert(islogical(params.manufacturing.enable) || isnumeric(params.manufacturing.enable), ...
            'manufacturing.enable必须为逻辑值');
        assert(params.manufacturing.grad_norm_weight >= 0, ...
            'manufacturing.grad_norm_weight必须为非负');
        assert(params.manufacturing.curvature_weight >= 0, ...
            'manufacturing.curvature_weight必须为非负');
        assert(params.manufacturing.gap_overlap_weight >= 0, ...
            'manufacturing.gap_overlap_weight必须为非负');
        assert(params.manufacturing.curvature_radius_min > 0, ...
            'manufacturing.curvature_radius_min必须为正');
        assert(params.manufacturing.gap_overlap_target > 0, ...
            'manufacturing.gap_overlap_target必须为正');
        assert(params.manufacturing.penalty_band_factor > 0, ...
            'manufacturing.penalty_band_factor必须为正');
    end
    
    % 日志级别
    valid_levels = {'DEBUG', 'INFO', 'WARN', 'ERROR'};
    assert(ismember(params.debug.log_level, valid_levels), ...
        '日志级别必须为 DEBUG/INFO/WARN/ERROR 之一');
    
    % 自洽性检查
    assert(params.levelset.transition_iter <= params.opt.max_iter, ...
        '转换迭代次数不应超过最大迭代次数');
    assert(params.levelset.reinit_freq_early <= params.levelset.reinit_freq_late, ...
        '前期重初始化频率应小于等于后期频率');
    
    % 检查点参数
    if params.debug.save_checkpoints
        assert(params.debug.checkpoint_interval > 0, ...
            '检查点保存间隔必须为正整数');
    end

    if isfield(params, 'init') && isfield(params.init, 'boundary_reconstruction')
        assert(ismember(lower(params.init.boundary_reconstruction), {'marching_squares_linear'}), ...
            'boundary_reconstruction当前仅支持marching_squares_linear');
    end

    if isfield(params, 'constraint')
        assert(ismember(lower(params.constraint.material_constraint_mode), {'strict'}), ...
            'material_constraint_mode当前仅支持strict');
        assert(ismember(lower(params.constraint.boundary_contact_policy), {'no-crossing'}), ...
            'boundary_contact_policy当前仅支持no-crossing');
        if strcmpi(params.constraint.material_constraint_mode, 'strict')
            assert(strcmpi(params.levelset.reinit_domain, 'masked'), ...
                'strict模式要求reinit_domain为masked');
        end
    end
    
    fprintf('✅ 参数验证通过\n');
end

